Catch exceptions when setting TTS language.
On some Galaxy S6, Android 6.0 it results in a
java.lang.IllegalArgumentException: Invalid int: "OS"
This is almost certainly an Android bug, but show
a message instead of crashing.